### ISSUE TITLE
Missed peer from nearby list on every crosswalk

### ISSUE THREAD

**Issue by ursoft** [ursoft/zwift-offline#5]
...even if no turns available (single road). 
Maybe we can improve nearby algo?

**Comment by oldnapalm** [comment]
I believe it's the normal game behavior, when the players are on different roads they don't appear in the nearby list.

I checked that place we tested, the route starts in road 4

![2022-04-04 18_35_30-Zwift](https://user-images.githubusercontent.com/38410858/161637639-65a4fe94-6624-4def-a0dd-15e4ac6ad9e9.png)

In the intersection area the road is 109

![2022-04-04 18_38_46-Zwift](https://user-images.githubusercontent.com/38410858/161637723-425fbb46-aa05-460c-af40-256a2c4a9b93.png)

Passing the crosswalk after the left turn, road is 6

![2022-04-04 18_39_41-Zwift](https://user-images.githubusercontent.com/38410858/161637876-8594f39f-67bf-4b6f-9d55-e8aacaff6fbc.png)

Notice in the video how the blue marks on the map still appear after they turn left (meaning their state is being received) but they disappear from nearby list

https://user-images.githubusercontent.com/38410858/161638142-60f1fb02-3d5a-474b-bfc5-a8b15b8b8a50.mp4

**Comment by ursoft** [comment]
Great investigation. It looks like bug in the map + possibly bug by design in the game (if ZA cuts off the "other road" playerstate from the nearby list). As I can understand is_nearby(), zoffline filters player states only by distance?

**Comment by oldnapalm** [comment]
Yes, looks like design flaw to me. Zoffline sends players on same course and inside a distance range.
